services:
  frontend-dev:
    image: ozzydoc/finstream-frontend:dev
    container_name: finstream-frontend-dev
    restart: unless-stopped
    # ports:
    #   - ${FRONTEND_DEV_PORT}:80
    networks:
      - dev
      - shared

networks:
  dev:
    external: true
  shared:
    external: true
