services:
  backend-prod-java:
    image: ozzydoc/finstream-backend-java:prod
    container_name: finstream-backend-prod-java
    restart: unless-stopped
    # ports:
    #   - ${BACKEND_PROD_PORT}:80
    networks:
      - prod
      - shared

networks:
  prod:
    external: true
  shared:
    external: true
