services:
  frontend-qa:
    image: ozzydoc/finstream-frontend:qa
    container_name: finstream-frontend-qa
    restart: unless-stopped
    # ports:
    #   - ${FRONTEND_QA_PORT}:80
    networks:
      - qa
      - shared

networks:
  qa:
    external: true
  shared:
    external: true
